// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movrr.API;

#nullable disable

namespace PetDb.Migrations
{
    [DbContext(typeof(PetDbContext))]
    partial class PetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movrr.API.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("DialCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CountryCode");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Movrr.API.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Movrr.API.PetBreed", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<byte>("TypeId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("PetBreed");
                });

            modelBuilder.Entity("Movrr.API.PetProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AvailableForBreeding")
                        .HasColumnType("bit");

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SexId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SexId");

                    b.ToTable("PetProfile");
                });

            modelBuilder.Entity("Movrr.API.PetType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("PetType");
                });

            modelBuilder.Entity("Movrr.API.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("LocationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("LocationId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Movrr.API.Sex", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Sex");
                });

            modelBuilder.Entity("Movrr.API.PetBreed", b =>
                {
                    b.HasOne("Movrr.API.PetType", "Type")
                        .WithMany("PetBreeds")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PetBreed_TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Movrr.API.PetProfile", b =>
                {
                    b.HasOne("Movrr.API.PetBreed", "Breed")
                        .WithMany("PetProfiles")
                        .HasForeignKey("BreedId")
                        .IsRequired()
                        .HasConstraintName("FK_PetProfile_BreedId");

                    b.HasOne("Movrr.API.Profile", "Owner")
                        .WithMany("PetProfiles")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_PetProfile_OwnerId");

                    b.HasOne("Movrr.API.Sex", "Sex")
                        .WithMany("PetProfiles")
                        .HasForeignKey("SexId")
                        .IsRequired()
                        .HasConstraintName("FK_PetProfile_SexId");

                    b.Navigation("Breed");

                    b.Navigation("Owner");

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("Movrr.API.Profile", b =>
                {
                    b.HasOne("Movrr.API.Country", "CountryCodeNavigation")
                        .WithMany("Profiles")
                        .HasForeignKey("CountryCode")
                        .IsRequired()
                        .HasConstraintName("FK_Profile_CountryCode");

                    b.HasOne("Movrr.API.Location", "Location")
                        .WithMany("Profiles")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Profile_LocationId");

                    b.Navigation("CountryCodeNavigation");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Movrr.API.Country", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Movrr.API.Location", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Movrr.API.PetBreed", b =>
                {
                    b.Navigation("PetProfiles");
                });

            modelBuilder.Entity("Movrr.API.PetType", b =>
                {
                    b.Navigation("PetBreeds");
                });

            modelBuilder.Entity("Movrr.API.Profile", b =>
                {
                    b.Navigation("PetProfiles");
                });

            modelBuilder.Entity("Movrr.API.Sex", b =>
                {
                    b.Navigation("PetProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
